### ISSUE TITLE
Does not want to read dump from AMAZON_S #

### ISSUE THREAD

**Issue by vido89** [rvalles/brntool#13]
I have ZTE ZXV10H201L it has AMAZON_S # prompt, when I start the tool it just hangs and write 

```
sudo python brntool.py --read=ZTE.dump --verbose --serial=/dev/ttyACM0 --addr=0xB0000000 --size=0x800000
[sudo] password for slobodan: 
Waiting for a prompt...
```

**Comment by rvalles** [comment]
I unfortunately cannot support devices I do not have.

Your best bet is to figure out how your device is different and adapt the code yourself.

Assuming the bootloader command syntax is otherwise the same, as you can get to the menu manually, maybe commenting out the get2menu call will get you there.

**Comment by vido89** [comment]
I tried commenting out lines 13 up to 23 and 61 and it does not work

**Comment by vido89** [comment]
@rvalles would you like to take a look over teamviewer ?

**Comment by rvalles** [comment]
It's been a long time since I touched this code at all, and I do not own any device brntool works with anymore.

 I suggest looking at the forks; the community has long taken over this tool.
